### ISSUE TITLE
"Add a User" functionality on Enrollment Page

### ISSUE THREAD

**Issue by gioeloja** [kiat/codeAssist#106]
**Adding a user in this view does not work.** 

![image](https://github.com/user-attachments/assets/fb8ca212-acbe-4741-9e63-c610261b83e1)

**The call to the POST endpoint, ```/create-enrollment``` is resulting in a KeyError.**

```
flask_container     | 192.168.65.1 - - [30/Oct/2024 15:06:27] "POST /create_enrollment HTTP/1.1" 500 -
flask_container     | Traceback (most recent call last):
flask_container     |   File "/usr/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__
flask_container     |     return self.wsgi_app(environ, start_response)
flask_container     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask_container     |   File "/usr/lib/python3.12/site-packages/flask/app.py", line 1476, in wsgi_app
flask_container     |     response = self.handle_exception(e)
flask_container     |                ^^^^^^^^^^^^^^^^^^^^^^^^
flask_container     |   File "/usr/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
flask_container     |     return cors_after_request(app.make_response(f(*args, **kwargs)))
flask_container     |                                                 ^^^^^^^^^^^^^^^^^^^^
flask_container     |   File "/usr/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
flask_container     |     return cors_after_request(app.make_response(f(*args, **kwargs)))
flask_container     |                                                 ^^^^^^^^^^^^^^^^^^^^
flask_container     |   File "/usr/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
flask_container     |     response = self.full_dispatch_request()
flask_container     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask_container     |   File "/usr/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
flask_container     |     rv = self.handle_user_exception(e)
flask_container     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask_container     |   File "/usr/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
flask_container     |     return cors_after_request(app.make_response(f(*args, **kwargs)))
flask_container     |                                                 ^^^^^^^^^^^^^^^^^^^^
flask_container     |   File "/usr/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
flask_container     |     return cors_after_request(app.make_response(f(*args, **kwargs)))
flask_container     |                                                 ^^^^^^^^^^^^^^^^^^^^
flask_container     |   File "/usr/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
flask_container     |     rv = self.dispatch_request()
flask_container     |          ^^^^^^^^^^^^^^^^^^^^^^^
flask_container     |   File "/usr/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
flask_container     |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
flask_container     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask_container     |   File "/usr/lib/python3.12/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
flask_container     |     resp = make_response(f(*args, **kwargs))
flask_container     |                          ^^^^^^^^^^^^^^^^^^^
flask_container     |   File "/usr/src/app/routes/course.py", line 161, in create_enrollment
flask_container     |     student_id = request.json["student_id"]
```

**To do:**
- See if there is a mismatch in the endpoint logic and the request body that we are sending. Our request body might not have the correct field, ```student_id``` included.

**Comment by gioeloja** [comment]
Closed out by #110
